module.exports = 
    [
        {
          from: "Los Angeles, Los Angeles Intl (LAX), United States",
          to: "New York, John F Kennedy Intl (JFK), United States",
          departureDate: "12-1-2022",
          arrivalDate: "12-1-2022",
          departureTime: "12:45",
          arrivalTime: "19:25",
          economySeats: 20,
          economyPrice: 145,
          businessSeats: 10,
          businessPrice: 874,
          firstClassSeats: 6,
          firstClassPrice: 1260,
          flightNumber: "DK123"
        },
        {
          from:  "New York, John F Kennedy Intl (JFK), United States",
          to:  "Los Angeles, Los Angeles Intl (LAX), United States",
          departureDate: "22-1-2022",
          arrivalDate: "22-1-2022",
          departureTime: "9:00",
          arrivalTime: "15:45",
         economySeats: 30,
          economyPrice:  140,
          businessSeats: 15,
          businessPrice:  880,
         firstClassSeats: 16,
           firstClassPrice:1200,
          flightNumber: "DK231"
        },
        {
          from: "New York, John F Kennedy Intl (JFK), United States",
          to: "London, Heathrow (LHR), United Kingdom",
          departureDate:"21-2-2022",
           arrivalDate:  "21-2-2022",
          departureTime:  "9:00",
           arrivalTime: "11:25",
           economySeats: 22,
         economyPrice:  740,
           businessSeats: 2,
          businessPrice: 2025,
          firstClassSeats: 5,
          firstClassPrice: 3900,
           flightNumber:  "DK895"
        },
        {
          from: "London, Heathrow (LHR), United Kingdom",
          to: "New York, John F Kennedy Intl (JFK), United States",
          departureDate: "6-3-2022",
          arrivalDate: "6-3-2022",
          departureTime: "8:05",
          arrivalTime: "19:50",
          economySeats: 43,
          economyPrice: 640,
          businessSeats: 26,
          businessPrice: 1950,
          firstClassSeats: 16,
          firstClassPrice: 3770,
          flightNumber: "DK753"
        },
        {
          from: "Cairo, Cairo Intl Apt (CAI), Egypt",
          to: "Dubai, Dubai Intl (DXB), United Arab Emirates",
          departureDate: "10-4-2022",
          arrivalDate: "10-4-2022",
          departureTime: "9:55",
          arrivalTime: "15:30",
          economySeats: 50,
          economyPrice: 255,
          businessSeats: 22,
          businessPrice: 636,
          firstClassSeats: 10,
          firstClassPrice: 827,
          flightNumber: "DK325"
        },
        {
          from: "Dubai, Dubai Intl (DXB), United Arab Emirates",
          to: "Cairo, Cairo Intl Apt (CAI), Egypt",
          departureDate: "18-4-2022",
          arrivalDate: "18-4-2022",
          departureTime: "12:55",
          arrivalTime: "18:00",
          economySeats: 50,
          economyPrice: 250,
          businessSeats: 22,
          businessPrice: 630,
          firstClassSeats: 10,
          firstClassPrice: 830,
          flightNumber: "DK833"
        },
        {
          from: "Munich, Franz Josef Strauss (MUC), Germany",
          to: "Paris, Charles De Gaulle (CDG), France",
          departureDate: "25-4-2022",
          arrivalDate: "25-4-2022",
          departureTime: "11:00",
          arrivalTime: "12:45",
          economySeats: 43,
          economyPrice: 90,
          businessSeats: 26,
          businessPrice: 280,
          firstClassSeats: 16,
          firstClassPrice: 500,
          flightNumber: "DK125"
        },
        {
          from: "Paris, Charles De Gaulle (CDG), France",
          to: "Munich, Franz Josef Strauss (MUC), Germany",
          departureDate: "2-5-2022",
          arrivalDate: "2-5-2022",
          departureTime: "7:00",
          arrivalTime: "10:15",
          economySeats: 43,
          economyPrice: 90,
          businessSeats: 26,
          businessPrice: 280,
          firstClassSeats: 16,
          firstClassPrice: 500,
          flightNumber: "DK774"
        }
    ]
